
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df=pd.read_csv(r'C:\Users\ragha\calls_911.csv')
pd.set_option('max_colwidth',9)
print(df.head())
print(df.info())
z=df['zip'].value_counts().head()
print(z)
t=df['title'].nunique()
print(t)
df['reason']=df['title'].apply(lambda title:title.split(':')[0])
print(df['reason'])
print(df['reason'].value_counts())
sns.countplot(x='reason',data=df)
plt.show()
time=pd.to_datetime(df['timeStamp'])
df['month']=time.apply(lambda x:x.month)
print(df['month'])
df['hour']=time.apply(lambda x: x.hour)
print(df['hour'])
df['day_of_week']=time.apply(lambda x:x.dayofweek)
print(df['day_of_week'])
df['day_of_week']=df['day_of_week'].map({0:'mon',1:'tue',2:'wed',3:'thur',4:'fri',5:'sat',6:'sun'})
print(df['day_of_week'])
sns.countplot(x='day_of_week',data=df,hue='reason',palette='viridis')
plt.show()
byMonth=df.groupby('month').count()

print(byMonth.head())
byMonth['lat'].plot()
plt.show()
sns.lmplot(x='month',y='twp',data=byMonth.reset_index())
plt.show()
d=pd.to_datetime(df['timeStamp'])
df['date']=d.apply(lambda x:x.date())
byDate=df.groupby('date').count()
print(byDate)
byDate['lat'].plot()
plt.show()
df[df['reason']=='Traffic'].groupby('date').count().plot()
plt.title('Traffic')
plt.show()
df[df['reason']=='Fire'].groupby('date').count().plot()
plt.title('Fire')
plt.show()
df[df['reason']=='EMS'].groupby('date').count().plot()
plt.title('EMS')
plt.show()
u=df.groupby(by=['day_of_week','hour']).count()['reason'].unstack()
print(u)
sns.heatmap(u,cmap='viridis')
plt.show()
sns.clustermap(u)
plt.show()
